config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kitties
  # Defines the root path route ("/")
  root "kitties#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitty.rb
class Kitty < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kitties_controller.rb
class KittiesController < ApplicationController
  
  def index
    @kitties = Kitty.all

    respond_to do |format|
      format.html
      format.xml { render :xml => @kitties }
      format.json { render :json => @kitties }
    end
  end

  def show
    @kitty = Kitty.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @kitty }
      format.json { render :json => @kitty }
    end
  end

  def new
    @kitty = Kitty.new
  end

  def create
    @kitty = Kitty.new(kitty_params)

    if @kitty.save
      redirect_to kitty_path(@kitty), notice: "Happy day, your kitten has been added!"
    else
      redirect_to new_kity_path, notice: "How did you mess this form up? Try again."
    end
  end

  def edit
  end

  def update
    @kitty = Kitty.find(params[:id])
    if @kitty.update(kitty_params)
      redirect_to kitty_path, notice: "Your kitty cat has been updated."
    else
      redirect_to kity_path, notice: "How did you mess this form up? Try again"
    end
  end

  def destroy
    @kitty = Kitty.find(params[:id])
    @kitty.destroy
    redirect_to root_path, notice: "Aw, you killed the cat. :("
  end

  private

  def kitty_params
    params.require(:kitty).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitties_helper.rb
module KittiesHelper
end

app/views/kitties/_form.html.erb
<%= form_with model: @kitty do |f| %>
  <%= f.label "Kitty's name:" %><br>
  <%= f.text_field :name %><br>
  <%= f.label "Age:" %><br>
  <%= f.number_field :age, in: 0..100 %><br>
  <%= f.label "Cuteness:" %><br>
  <%= f.range_field :cuteness, in: 1..10 %><br>
  <%= f.label "Softness:" %><br>
  <%= f.range_field :softness, in: 1..10 %><br>
  <%= f.submit "Save!" %>
<% end %>

app/views/kitties/index.html.erb
Welcome to Kitty Creator!<br>
<ul>
<% @kitties.each do |kitty| %>
  <li><%= link_to kitty.name, kitty_path(kitty) %><br><br>
  <%= button_to "Delete Kitty", kitty_path(kitty), :method => :delete %> </li> <br><br>
<% end %>
</ul>

app/views/kitties/new.html.erb
How excited must your kitty be? Finally, added to this list of kittens!<br>
<%= render "form", kitty: @kitty %>

app/views/kitties/show.html.erb
Hi there, <%= @kitty.name %>!<br><br>

<%= @kitty.name %> is <%= @kitty.age %> years old.<br>
<%= @kitty.name %> has a cuteness of <%= @kitty.cuteness %> and a softness of <%= @kitty.softness %>.
<br>
<br>
<br>
Edit kitty?<br>
<%= render "form", kitty: @kitty %><br><br>
<%= button_to "Delete Kitty", kitty_path(@kitty), :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kitten</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "View the list of kittens", root_path %>  <%= link_to "Add a kitten", new_kitty_path %><br><br>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>